server:
  port: 8071
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kael-tv/fitnetwork-config
          default-label: main
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}